### ISSUE TITLE
"Select All" button toggles even when there are no bookmarks

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#181]
**Describe the bug**
"Select All" button toggles to "Deselect All" even when there are no bookmark images to select. 

This only happens when there were some bookmarks at the start of the session and the user has deleted them.

**To Reproduce**
1. Go to the bookmarks section (make sure there is at least one bookmark).
2. Click on the "Select All" button.
3. Click on the "Delete" button to delete them.
4. Now, click on the "Deselect all" button.
5. See error

**Expected behavior**
The "Select All" button should not toggle to "Deselect all" in this case.

**GIF**
![ezgif com-crop (3)](https://user-images.githubusercontent.com/34679965/76203958-8305f200-621d-11ea-88d7-4df56f8e9899.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Chrome v80.0.3987.122

**Comment by lakshaybits** [comment]
Hi @makkoncept , Can i work on this issue?

**Comment by makkoncept** [comment]
@lakshaybits go ahead.

**Comment by lakshaybits** [comment]
@makkoncept  Can you please check, I think this issue is solved in the recent PR.

**Comment by makkoncept** [comment]
The issue still persists but in a different form. The button should read the default "Select all" when there are no bookmarks to select.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/34679965/76685069-e2f20380-6636-11ea-80b8-f7663524f4f3.gif)

**Comment by lakshaybits** [comment]
Okay, will work on it.
